version: "3.9"

services:
  # --- Servicio de Base de Datos MySQL ---
  db:
    build:
      context: ./database
    container_name: cc_mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD_FILE: ${MYSQL_ROOT_PASSWORD_FILE}
      MYSQL_PASSWORD_FILE: ${MYSQL_PASSWORD_FILE}
      BACKUP_USER: ${BACKUP_USER}
      BACKUP_PASSWORD_FILE: ${BACKUP_PASSWORD_FILE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./database/init_backup_user.sh:/docker-entrypoint-initdb.d/init_backup_user.sh:ro
    secrets:
      - mysql_root_password
      - mysql_app_password
      - mysql_backup_password
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 10

  # --- Servicio de API (FastAPI) ---
  api:
    build:
      context: ./backend
    container_name: cc_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_ENV: ${APP_ENV}
      APP_PORT: ${APP_PORT}
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_PASSWORD_FILE: ${MYSQL_PASSWORD_FILE}
      CORS_ORIGINS: ${CORS_ORIGINS}
      BACKUP_DIR: ${BACKUP_DIR}
      BACKUP_ACTOR: ${BACKUP_ACTOR}
    ports:
      - "8000:8000"
    volumes:
      - backup_data:${BACKUP_DIR}
    restart: unless-stopped
    secrets:
      - mysql_app_password
      - jwt_secret

  # --- Servicio Frontend (NGINX) ---
  web:
    build:
      context: ./frontend
    container_name: cc_frontend
    depends_on:
      api:
        condition: service_started
    ports:
      - "8080:443"
    restart: unless-stopped

  # --- Servicio de Backups automáticos ---
  backup:
    build:
      context: ./backup
      dockerfile: cronjob.Dockerfile
    container_name: cc_backup
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_HOST: db                # nombre del servicio de la DB
      MYSQL_USER: ${BACKUP_USER}
      MYSQL_PASSWORD: ${BACKUP_PASSWORD}
      MYSQL_PASSWORD_FILE: ${BACKUP_PASSWORD_FILE}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      BACKUP_DIR: ${BACKUP_DIR}
      BACKUP_ACTOR: ${BACKUP_ACTOR}
    volumes:
      - backup_data:/backups        # aquí se guardan los .sql
    restart: unless-stopped
    secrets:
      - mysql_backup_password

volumes:
  db_data:
  backup_data:

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_app_password:
    file: ./secrets/mysql_app_password.txt
  mysql_backup_password:
    file: ./secrets/mysql_backup_password.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt
